[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".env.local"]

[images]
  remote_images = [
    "https://xsgames.co/randomusers/assets/avatars/**",
    "https://cdn.shortpixel.ai/**",
    "https://weandthecolor.com/**",
    "https://marketplace.canva.com/**",
    "https://www.portfoliowebsitetemplate.com/**",
    "https://designshack.net/**",
    "https://templatefor.net/**",
    "https://cdn.dribbble.com/**",
    "https://www.hostinger.com/**",
    "https://www.dreamhost.com/**",
    "https://colorlib.com/**",
    "https://cdn.searchenginejournal.com/**",
    "https://ui-avatars.com/**"
  ]
