[images]
  remote_images = ["*"]

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js dynamic routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Increase functions timeout for API routes
[functions]
  included_files = ["node_modules/mongodb/**"]
  node_bundler = "esbuild"
  external_node_modules = ["bcrypt", "mongodb", "mongoose"]
