[images]
  remote_images = ["https://ui-avatars.com/**", "https://placehold.co/**", "https://repository-images.githubusercontent.com/**", "https://marketplace.canva.com/**", "https://weandthecolor.com/**", "https://www.unsell.design/**", "https://slidestack-prod.s3.amazonaws.com/**"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
